# Generated by Django 4.2.7 on 2023-11-11 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_message", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="read",
            new_name="is_read",
        ),
    ]
